/*
  SUNLIT CITRUS ATLAS — route pages.
  Each supporting page extends the homepage’s calm editorial field-guide pattern with truthful, static-safe calls to action.
*/
import { ArrowRight, ArrowUpRight, Check, Mail, MapPin, Phone, Search, Send } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link } from "wouter";
import { SiteShell } from "../components/SiteShell";

type PageType = "buy" | "sell" | "search" | "communities" | "agents" | "resources" | "careers" | "about" | "contact" | "privacy-policy" | "terms-of-use" | "notfound";

const assets = {
  hero: "/manus-storage/c21-citrus-hero-estate_b43f73af.jpg",
  interior: "/manus-storage/c21-citrus-interior_dc2ded1c.jpg",
  neighbourhood: "/manus-storage/c21-citrus-neighbourhood_881ec5cd.jpg",
  detail: "/manus-storage/c21-citrus-detail_b3fce7fb.jpg",
};

const content: Record<PageType, { eyebrow: string; title: React.ReactNode; intro: string; image: string; imageAlt: string; label: string; steps: { title: string; body: string }[]; primary: string; secondary: string; cta: string; ctaHref: string }> = {
  buy: { eyebrow: "For buyers", title: <>Start with a place<br />you can <em>picture.</em></>, intro: "A better search is more than a collection of listings. It begins with your everyday needs, your future plans, and a clear view of the choices ahead.", image: assets.interior, imageAlt: "Contemporary home interior", label: "Your buying wayfinder", steps: [{ title: "Set your compass", body: "Clarify the location, lifestyle, and financial questions that will shape a more useful search." }, { title: "Explore with context", body: "Use the live property search, then connect with a local guide when a home deserves a closer look." }, { title: "Move with clarity", body: "Bring each next step into focus—from offer through closing—without losing sight of the larger plan." }], primary: "Search live homes", secondary: "Talk to an agent", cta: "Start your search", ctaHref: "https://c21citrus.com/search/" },
  sell: { eyebrow: "For sellers", title: <>A sale deserves<br />a <em>considered launch.</em></>, intro: "A successful sale brings together timing, presentation, pricing, and communication. We help you start with the details that can make a difference.", image: assets.detail, imageAlt: "Keys and a citrus detail on a dark stone surface", label: "Your seller launch plan", steps: [{ title: "Understand your position", body: "Begin with a current market conversation and an informed view of what your property could command." }, { title: "Prepare the story", body: "Shape a presentation that makes the property’s strongest qualities immediately clear." }, { title: "Launch with intention", body: "Coordinate the market debut and stay connected through the questions, decisions, and next steps." }], primary: "Get a home value", secondary: "Plan your sale", cta: "Request a valuation", ctaHref: "https://homesinlosangelesarea.hifello.com/p/oj/65a073e677ad1a0024e92307" },
  search: { eyebrow: "Property search", title: <>Let the search<br />take <em>shape.</em></>, intro: "Use the live C21 Citrus search to explore active homes across Southern California. Return here whenever you need a human perspective on what you are seeing.", image: assets.hero, imageAlt: "Southern California estate at golden hour", label: "A search with a local lens", steps: [{ title: "Search broadly", body: "Explore current inventory by city, neighborhood, or ZIP code through the connected live search." }, { title: "Save the signals", body: "Notice patterns in location, condition, timing, and price before narrowing the list." }, { title: "Get perspective", body: "Connect with a local C21 Citrus guide when a listing begins to feel like a possibility." }], primary: "Open live home search", secondary: "Talk to an agent", cta: "Search current homes", ctaHref: "https://c21citrus.com/search/" },
  communities: { eyebrow: "Local field guide", title: <>The right place has<br />its own <em>rhythm.</em></>, intro: "From foothill neighborhoods to connected city centers, we help make sense of the small details that change the way a place feels day to day.", image: assets.neighbourhood, imageAlt: "Tree-lined Southern California neighborhood", label: "Explore the region", steps: [{ title: "San Dimas", body: "Foothill energy, a familiar local pace, and plenty of space to make a routine feel grounded." }, { title: "Glendora", body: "A village-minded setting where tree-lined streets and mountain views shape the everyday experience." }, { title: "La Verne", body: "Heritage character and a connected community feel, close to the places that matter." }], primary: "Search by area", secondary: "Ask about a community", cta: "Explore live inventory", ctaHref: "https://c21citrus.com/search/" },
  agents: { eyebrow: "Our people", title: <>Guidance starts<br />with a <em>good conversation.</em></>, intro: "C21 Citrus Realty brings together people who understand that local real estate is built on listening well, preparing carefully, and staying present through the details.", image: assets.interior, imageAlt: "Elegant contemporary home interior", label: "Meet C21 Citrus", steps: [{ title: "A personal point of view", body: "Share what matters to you and start with advice calibrated to the decision in front of you." }, { title: "A connected office", body: "Work with a locally rooted organization that keeps people, neighborhoods, and long-term relationships close." }, { title: "A clear next step", body: "Use a quick conversation to decide whether a search, valuation, or market discussion is the right place to begin." }], primary: "Contact the office", secondary: "Browse resources", cta: "Connect with C21 Citrus", ctaHref: "/contact" },
  resources: { eyebrow: "Local resources", title: <>Useful context for<br />what comes <em>next.</em></>, intro: "Good decisions come from knowing what to ask. Use these practical starting points to get familiar with the buying, selling, and local-market conversation.", image: assets.detail, imageAlt: "Thoughtful real estate planning materials", label: "Keep exploring", steps: [{ title: "Buying process", body: "Build a working understanding of the path from an early search through inspections, financing, and closing." }, { title: "Selling process", body: "See how preparation, pricing, presentation, and timing come together in a sale plan." }, { title: "Relocation", body: "Bring the important questions about a new area into one calm, useful conversation." }], primary: "Buying guidance", secondary: "Selling guidance", cta: "Connect for local context", ctaHref: "/contact" },
  careers: { eyebrow: "Careers at C21 Citrus", title: <>Build a career<br />with <em>room to grow.</em></>, intro: "Whether you are starting fresh or looking for a more connected home for your business, C21 Citrus creates space for professional momentum and local relationships.", image: assets.neighbourhood, imageAlt: "Southern California neighborhood", label: "A more connected career", steps: [{ title: "Start with curiosity", body: "Tell us about the chapter you are building and the support that would make the most difference." }, { title: "Find your footing", body: "Explore a culture focused on practical tools, ongoing learning, and a network that shares knowledge." }, { title: "Grow locally", body: "Build a durable business by staying close to the people and places you serve." }], primary: "Start a conversation", secondary: "Contact the office", cta: "Explore opportunities", ctaHref: "/contact" },
  about: { eyebrow: "About C21 Citrus", title: <>Locally rooted.<br /><em>Forward looking.</em></>, intro: "C21 Citrus Realty brings an established local presence to every conversation about Southern California real estate. The work begins with place, people, and a plan that makes sense.", image: assets.hero, imageAlt: "California home in golden hour", label: "The C21 Citrus approach", steps: [{ title: "Listen before leading", body: "Our advice begins with the life, questions, and tradeoffs behind the transaction." }, { title: "Stay close to the market", body: "We look beyond a listing screen to the local context that changes the picture." }, { title: "Think past closing", body: "Our role is to make a next move feel more supported, wherever it leads." }], primary: "Meet the team", secondary: "Contact C21 Citrus", cta: "Start a conversation", ctaHref: "/contact" },
  contact: { eyebrow: "Contact C21 Citrus", title: <>Let’s begin with<br />a <em>conversation.</em></>, intro: "Tell us what you are considering. We will help you identify the right first step and connect you with the right local resource.", image: assets.detail, imageAlt: "Key and citrus detail", label: "A simple place to begin", steps: [{ title: "Search or sale", body: "Ask about a property search, a potential listing, or what the market may mean for your move." }, { title: "Local questions", body: "Bring us your questions about a neighborhood, a next step, or an opportunity to connect." }, { title: "Office visit", body: "Reach the C21 Citrus office by phone or email whenever that feels easier." }], primary: "Email the office", secondary: "Call 909.592.8500", cta: "Send an inquiry", ctaHref: "/contact" },
  "privacy-policy": { eyebrow: "Privacy", title: <>Your information,<br /><em>handled with care.</em></>, intro: "This static demonstration site does not collect, store, or transmit visitor information. The live services linked from the site may maintain their own privacy policies.", image: assets.detail, imageAlt: "Abstract architectural detail", label: "Privacy at a glance", steps: [{ title: "No server-side collection", body: "This frontend-only experience does not process form submissions or create visitor accounts." }, { title: "Linked services", body: "External search and valuation services operate independently and may have their own policies." }, { title: "Contact questions", body: "For questions related to C21 Citrus business operations, contact the office directly." }], primary: "Email the office", secondary: "Back home", cta: "Contact C21 Citrus", ctaHref: "/contact" },
  "terms-of-use": { eyebrow: "Terms of use", title: <>Use the site<br /><em>with clarity.</em></>, intro: "This is a static presentation of C21 Citrus Realty content. Links to property search, home valuation, and social platforms direct visitors to their respective live services.", image: assets.hero, imageAlt: "Exterior of a modern home", label: "Site terms", steps: [{ title: "Information only", body: "Material on this site provides general information and should not be considered legal, financial, or real estate advice." }, { title: "External links", body: "Property and valuation resources are hosted by external services and are governed by their own terms." }, { title: "Contact the office", body: "Reach out to the C21 Citrus office for current property, agency, and service information." }], primary: "Contact the office", secondary: "Back home", cta: "Start a conversation", ctaHref: "/contact" },
  notfound: { eyebrow: "Page not found", title: <>This route is<br />still <em>being mapped.</em></>, intro: "The page you requested is not available in this site experience. Head home or open the live property search to keep exploring.", image: assets.neighbourhood, imageAlt: "A quiet local street", label: "Find your route", steps: [{ title: "Return home", body: "Find buying, selling, career, and community paths from the main field guide." }, { title: "Search live homes", body: "Open the connected property search to see current inventory." }, { title: "Contact C21 Citrus", body: "Ask the office where to find the resource you need." }], primary: "Return home", secondary: "Search homes", cta: "Go to the homepage", ctaHref: "/" },
};

const routeFraming: Record<PageType, { stepsTitle: React.ReactNode; ctaTitle: React.ReactNode; ctaCopy: string }> = {
  buy: { stepsTitle: <>Follow the clues<br />that <em>make a place yours.</em></>, ctaTitle: <>A property search<br />with a <em>local point of view.</em></>, ctaCopy: "Open the live search, then bring a promising address to C21 Citrus for a more informed next step." },
  sell: { stepsTitle: <>Set the launch<br />up <em>to travel well.</em></>, ctaTitle: <>Your sale has<br />a <em>starting line.</em></>, ctaCopy: "A current valuation is a practical way to begin the conversation about timing, price, and presentation." },
  search: { stepsTitle: <>Look past the list<br />to see the <em>pattern.</em></>, ctaTitle: <>Every listing is<br />a <em>possible route.</em></>, ctaCopy: "Use the live search as a starting point, then ask for context when a property begins to stand out." },
  communities: { stepsTitle: <>Read the region<br />like a <em>field guide.</em></>, ctaTitle: <>Find the setting<br />for your <em>next chapter.</em></>, ctaCopy: "Search current opportunities across the region, or contact the office for a more personal local introduction." },
  agents: { stepsTitle: <>Find the person<br />for the <em>right conversation.</em></>, ctaTitle: <>Local insight travels<br />further <em>together.</em></>, ctaCopy: "A simple conversation can help bring the person, property, and next step into clearer alignment." },
  resources: { stepsTitle: <>Bring better questions<br />to the <em>table.</em></>, ctaTitle: <>Clarity is a good<br /><em>place to begin.</em></>, ctaCopy: "Use a guide to get oriented, then reach out for the local context that turns general information into a useful plan." },
  careers: { stepsTitle: <>Give your work<br />a <em>local foundation.</em></>, ctaTitle: <>The next chapter<br />starts with <em>a hello.</em></>, ctaCopy: "Tell the office what you are building and start exploring what a more connected brokerage home could look like." },
  about: { stepsTitle: <>The work is local.<br />The view is <em>long-term.</em></>, ctaTitle: <>A local office with<br />an <em>open door.</em></>, ctaCopy: "C21 Citrus is here when you need a clearer read on what is happening now and what could come next." },
  contact: { stepsTitle: <>Bring the question<br />that is <em>on your mind.</em></>, ctaTitle: <>A conversation is<br />the <em>first marker.</em></>, ctaCopy: "We will help you sort the first practical step from the many things that may be on your mind." },
  "privacy-policy": { stepsTitle: <>The useful details,<br />held <em>in the open.</em></>, ctaTitle: <>Privacy questions<br />deserve <em>plain answers.</em></>, ctaCopy: "If you need more information about C21 Citrus business operations, the office is the right place to ask." },
  "terms-of-use": { stepsTitle: <>A clear route<br />for <em>using the site.</em></>, ctaTitle: <>Need a more current<br /><em>local answer?</em></>, ctaCopy: "Connect with C21 Citrus directly for current information about properties, agency, and services." },
  notfound: { stepsTitle: <>A missed turn is<br />still <em>part of the route.</em></>, ctaTitle: <>Let’s find the<br /><em>right direction.</em></>, ctaCopy: "Return to the field guide or open the live property search to keep exploring Southern California." },
};

function ContactForm() {
  const [sent, setSent] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", message: "" });
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const subject = encodeURIComponent(`Website inquiry from ${form.name || "a visitor"}`);
    const body = encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\n\n${form.message}`);
    window.location.href = `mailto:oj@c21citrus.com?subject=${subject}&body=${body}`;
    setSent(true);
  };
  return <form className="contact-form" onSubmit={submit}>
    <div><label htmlFor="name">Your name</label><input id="name" required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Name" /></div>
    <div><label htmlFor="email">Email address</label><input id="email" required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="name@example.com" /></div>
    <div><label htmlFor="message">What can we help with?</label><textarea id="message" required rows={4} value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} placeholder="Buying, selling, a local question…" /></div>
    <button className="button button-dark" type="submit">Open your email app <Send size={16} /></button>
    {sent && <p className="form-note"><Check size={15} /> Your email app should now be ready to send this message.</p>}
  </form>;
}

export default function SectionPage({ type }: { type: PageType }) {
  const page = content[type];
  const framing = routeFraming[type];
  const isContact = type === "contact";
  const primaryHref = page.ctaHref.startsWith("http") ? page.ctaHref : page.ctaHref;
  return <SiteShell>
    <main id="main-content" className={`page-main page-${type}`}>
      <section className="page-hero">
        <div className="page-hero-copy"><p className="eyebrow"><span /> {page.eyebrow}</p><span className="page-route-code">C21 / {page.label}</span><h1>{page.title}</h1><p>{page.intro}</p><div className="page-hero-actions"><a className="button button-dark" href={primaryHref} target={page.ctaHref.startsWith("http") ? "_blank" : undefined} rel={page.ctaHref.startsWith("http") ? "noreferrer" : undefined}>{page.cta} <ArrowRight size={17} /></a><Link className="text-action" href="/contact">{page.secondary} <ArrowUpRight size={16} /></Link></div></div>
        <figure className="page-hero-image"><img src={page.image} alt={page.imageAlt} /><div className="page-route-graphic" aria-hidden="true"><span /><span /><span /></div><figcaption>{page.label}<span>↗</span></figcaption></figure>
      </section>
      <section className="page-steps">
        <div className="steps-heading"><p className="eyebrow"><span /> {page.label}</p><h2>{framing.stepsTitle}</h2></div>
        <div className="steps-list">{page.steps.map((step, index) => <article key={step.title}><span>0{index + 1}</span><h3>{step.title}</h3><p>{step.body}</p></article>)}</div>
      </section>
      {isContact && <section className="contact-section"><div><p className="eyebrow"><span /> Send a note</p><h2>One message can<br />set the <em>route.</em></h2><p>On this static site, submitting the form opens your default email app with your inquiry addressed to the office. You remain in control before anything is sent.</p><div className="contact-details"><a href="tel:+19095928500"><Phone size={17} /> 909.592.8500</a><a href="mailto:oj@c21citrus.com"><Mail size={17} /> oj@c21citrus.com</a><p><MapPin size={17} /> 1700 East Walnut Avenue<br />El Segundo, CA 90245</p></div></div><ContactForm /></section>}
      {!isContact && <section className="page-cta"><div><p className="eyebrow light"><span /> C21 Citrus Realty</p><h2>{framing.ctaTitle}</h2></div><div><p>{framing.ctaCopy}</p><Link href="/contact" className="button button-gold">Start a conversation <ArrowRight size={17} /></Link></div></section>}
    </main>
  </SiteShell>;
}
